version: "3"

services:
  product:
    build: ./product-service
    depends_on:
      - mongo

  python:
    build: ./product-save-service
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  listing:
    build: ./listing-service
    depends_on:
      - mongo

  # webapp:
  #   build: ./webapp-service
  #   links:
  #     - product
  #   depends_on:
  #     - product
  #   ports:
  #     - "4200:4200"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product
      - mongo
      - listing
      - python
      # - webapp
